[package]
name = "rate-my-bistro-server"
version = "0.1.0"
#authors= TODO
edition = "2018"

[dependencies]
rocket = "0.4"
chrono = "0.4"
arangors = "0.4.5"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["full"] }
