[debug]
address = "127.0.0.1"
port = 8001
workers = 1
keep_alive = 0
log_level = "normal"

[global.databases.arango]
url = "http://localhost:8529"
username = "bistrouser"
password = "bistropassword"
use_jwt = false
