[default]
address = "0.0.0.0"
port = 8001
log_level = "normal"

[debug]
workers = 1
keep_alive = 0

[global.databases.arango]
url = "http://localhost:8529"
username = "bistrouser"
password = "bistropassword"
use_jwt = false
