[package]
name = "bistro-service"
version = "0.1.0"
authors = ["Ansgar Sachs <ansgar.sa@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-swagger = "0.2.1"
