openapi: 3.0.1

info:
    title: "Rate My Bistro: Server"
    version: 0.1.0
    description: "Serves the 'Rate My Bistro: App'"

servers:
  - url: http://localhost:9005

paths:
    /menus/{id}:
        get:
            operationId: retrieveMenuByIdRequest
            tags: [Menu]
            description: Retrieves a single menu by its Id
            parameters:
                - $ref: "#/components/parameters/IdParam"
            responses:
                200:
                    $ref: "#/components/responses/MenuResponse"
                400:
                    $ref: "#/components/responses/BadArgument"
                422:
                    $ref: "#/components/responses/UnprocessableEntity"

    /menus:
        get:
            operationId: retrieveMenusByDateRangeRequest
            tags: [Menu]
            description: Retrieves a set of menus by a date range
            parameters:
              - $ref: "#/components/parameters/FromDateParam"
              - $ref: "#/components/parameters/ToDateParam"
            responses:
              200:
                  $ref: "#/components/responses/MenuListResponse"
              400:
                  $ref: "#/components/responses/BadArgument"
              422:
                  $ref: "#/components/responses/UnprocessableEntity"


components:
    schemas:
        Error:
            type: object
            properties:
                code:
                    type: string
                message:
                    type: string
            required:
                - code
                - message

        MenuList:
            type: array
            items:
              $ref: "#/components/schemas/Menu"

        Price:
            type: object
            description: Combination of price and currency
            properties:
                value:
                    type: float
                    description: Value represented in 0.99
                currency:
                    type: string
                    enum: [EUR]
                    description: Set of currently supported currencies

        Menu:
            type: object
            properties:
                id:
                    type: string
                    format: uuid
                    description: A unique Identifier for the menu
                servedAt:
                    type: date
                    description: Date when Menu is served in YYYY-MM-DD
                name:
                    type: string
                    description: Name of Menu
                supplements:
                    type: array
                    items:
                      type: object
                      description: A supplement which can be added to the menu
                      properties:
                          name:
                              type: string
                              description: Brief information about the supplement
                          price:
                              $ref: "#/components/schemas/Price"
                image:
                    type: string
                    description: Url where an image of the Menu is located
                price:
                    $ref: "#/components/schemas/Price"


    responses:
        UnprocessableEntity:
            description: Given input type is correct, but is not matching expectations
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"

        BadArgument:
            description: Given input type is incorrect
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"

        MenuResponse:
            description: A single menu
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Menu"'

        MenuListResponse:
            description: A list of menus that are served during the given time range
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/MenuList"

  parameters:
      IdParam:
          in: path
          name: id
          description: Parameter that describes a specific entity ID
          required: true
          schema:
            type: string
            format: uuid

      FromDateParam:
          in: query
          name: from
          description: Parameter that describes an inclusive start date range in YYYY-MM-DD
          required: true
          schema:
              type: string
              format: date

      ToDateParam:
          in: query
          name: to
          description: Parameter that describes an inclusive end date range in YYYY-MM-DD
          required: true
          schema:
              type: string
              format: date
